/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0+p48-gd3223e31
 *
 * Project: 'Project.Debug+STM32F303K8Tx' 
 * Target:  'Debug+STM32F303K8Tx' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f3xx.h"

/* Keil::Device&Standalone:Startup@1.11.3 */
#define RTE_DEVICE_STARTUP_STM32F3XX    /* Device Startup for STM32F3 */


#endif /* RTE_COMPONENTS_H */
